{% set version = "0.2.0" %}

package:
  name: hdfs3
  version: "{{ version }}"

source:
  fn: hdfs3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdfs3/hdfs3-{{ version }}.tar.gz
  sha256: 4e74d3dccfab68596c11d1b2e62420bcc36fbd2692aa2771abc27e08d43bc631

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  # This packages uses libhdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [not linux]

requirements:
  build:
    - python
    - setuptools
    - libhdfs3 2.3

  run:
    - python
    - libhdfs3 2.3

test:
  imports:
    - hdfs3

about:
  home: https://github.com/dask/hdfs3
  license: BSD 3-Clause
  summary: Python wrapper for libhdfs3

extra:
  recipe-maintainers:
    - mrocklin
    - martindurant
    - koverholt
