{% set version = "0.1.3" %}

package:
  name: hdfs3
  version: "{{ version }}"

source:
  fn: hdfs3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdfs3/hdfs3-{{ version }}.tar.gz
  md5: c80a0a7ff737b21fd1d8035dec2cecd3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  # This packages uses libhdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [not linux]

requirements:
  build:
    - python
    - setuptools
    - libhdfs3

  run:
    - python
    - libhdfs3

test:
  imports:
    - hdfs3

about:
  home: https://github.com/dask/hdfs3
  license: BSD 3-Clause
  summary: Python wrapper for libhdfs3

extra:
  recipe-maintainers:
    - mrocklin
    - martindurant
    - koverholt
