travis:
  secure:
    BINSTAR_TOKEN: HeCiwcfnckJPK2iKD+5LbHX9wQNfqYC3uICXQBPKfiVO7PCFsbFw3LnGDgbECW0bqFI99OdS+i2F3REhNsD+84pGPeF7EBaU/qISy7FRwDkivQtCPgDTy/eFmM3xrACJ59Ifzqk4LdqzDItnH9vTZS9i9kIAbwcYasH9M84BN/mpdM1joW2+ndvpqasQjNbyyI1ZOS6L3bHFhlU2fNBBbXoOaoSa7boMNvVM8Gi5auI7+SjhLbAZg4OpBriYFfB3ikNNiAjVa0Zw3GFW5JEzaiJiKwzKI5xKnzXs9x1EOxtrEDuINBYjNCgY/Tiwo4XNAsU/RVglSww/XcNn3X3J59NVIe+inXAH6Xbpozv8pLPSyJbLbqQaN188aimu/1dD6GQ4U+hkTjApulk7yzkDYcHsCYySo2pe13YIMZ4UIAbzL2wIMwu6AADgy82tFwQPTBFFM5vYqBBrxc1TNV2W3jw2Uc5PlpDVYMIOnDOq7pQ6Zw2nxno12efqbPUjbcKuTloDHkL37kpqhCYTO8aki+x/DuGtpOMD00DfXMbqHPc/ZJXyHKhwhamuqBghp+WP8yoeJ1/h3Pd+6Hftm4fZCJO8v63We97lDJd04SrzTZ03eirVFKPKlBsMwPtdOngBmlIYI4rdcFaXDkhXpToBPxVWndOSvRalmqvG8dDOvCI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
