travis:
  secure:
    BINSTAR_TOKEN: Wcj6gPMfNMUz3kaE7/0aFXyFiKv1mgn0Okx12wrtqpT6sn36jNGkPK8TllLfOETrHfxQeCVWLK0DQ/9ULTeUvx14D01u9xxyq/yQtgdnPrwiva6gy7NZFmImOfBNyeGUkQDOJHwIHx8EqZlNWJMDjL9tXSlTHcCE09KN4BdvmYj5EnXzxgOWK/oeWHizv8AqQI4IG8TMxaAb4RGejGsQwLX3xcGOFNDVUxwd9fGLrfaI5tCPw/js1jlINt6Xw7+WmLmIjQNWtT+fYeMBRIE9ie64hRAxVFOlY643RSYbn9VkecgqHawQlKN9ci+odYRZsXQx6IA9t01oAf6UKD7R6qTvzPja4Y6ng84QIn/j3eSOSRGgKB3lfNf/y15nHH+vXXhL1f6ONistfAOa02Ildv46kV+ZWGP72TM2In4hggSlCDE/irlH9AaMIDmPd6lL8LiSYas8expqwjMp/jKurBuA0JPQNe4Vbx3dvVIhivBtByxtiG1EoAahh/F5LGbGC1m6KUT4+B9iArqnOD1vzLD+U7h6+l7J9HGx00s8u+MNR9e/lorRbctBfvGmKW9YOdzvF8ATJj+c+y+atK23tZSNffRXgIr2ldR1iuoakIhL/2FheMcLUYypAP6E9BSxg1lTTMnvIxze0ibYEYgKKqQi2zMDi+EOO7ZEUWl0CN4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
